### ISSUE TITLE
When i Use your launcher game does not go into full screen, girls are missing clothes and i am unable to save or load the game.

### ISSUE THREAD

**Issue by ThepunisherNL** [kkdevs/Patchwork#12]
Like the title suggests i am unable to go into full screen with your launcher. When i enable full screen in the settings it still shows the windows task bar. I am also unable to load or save a game. When i try to save or load a game the menu button simply does not respond. Also girls have no clothers, they are only wearing bra's and panties. I am running bepinex 4 and my game version is 3.0

**Comment by ezdiy** [comment]
Plugin or mod conflict. Try unchecking all the things in scripts tab marked 'DLL', ie except the scripts at the bottom. That may or may not help with the save/load.

Missing clothes usually means corrupted zipmod or hardmod is loaded, while vanilla game can survive this, pw does not. So far the following seem to cause issues like you have:

* A lot of uncensors which have only oo_ file without materials in mm_
* Tongue texture 
* Slender armpit fixer
* Pubic hair fixer 
* Mecha Line Suntan Fixer

To remove mods, uncheck the unzip script (it would re-extract whatever you delete otherwise), and start deleting folders in `patchwork/mod` which is what is actually used here.

Future versions will try to detect and fix this automatically, so if you don't want to do this by hand, wait until then.

Finally, you can enable `[SPAM]` in advanced tab, run the game and go into maker wait until the errors appear, then quit the game. Then post file `Koikatu_Data/output_log.txt` it's usually possible to discern what went wrong from that.

**Comment by ezdiy** [comment]
no resp

**Comment by Bluhmanman** [comment]
I'm getting similar issues, but the circumstances are a little different:

- In the character editors, costumes created that utilize mods only partially load. Any components that are modded don't seem to load correctly. Costumes that don't utilize any mods will load as intended.
- In studio, attempting to load any outfit (modded or not) does not work and simply removes all clothing/accessories.
- I can still load/save games, use fullscreen, etc.
- The costume loading issues remain even when all mods/plugins are disabled.
